# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1039ae7a52da416d2af477dcd1c0307b89e31a874f20287758860a9582c87ef8c31438b96f120120986764a571423db5e25ab6543eaca59d0378819a653971d3

test:
  secret_key_base: 436649e14eade45b2f1a4152a35e139bb97ec48aed65fc6a87e022ba26e54da6389ed3404a529aba4070e4302b255c8910d63f2cb94769b5b3db5fea97402959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
